name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'asn/'
  pull_request:
    branches: [ main ]
    paths:
      - 'asn/'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build asn --tag asn:$(date +%s)
